### ISSUE TITLE
Markbot is being mean

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/exploding-robot-head#1]
Hey!

I'm having issues with Markbot. When I run my code through it it says it looks visually different but when I open the index in Chrome and Firefox it looks and acts like the example.

@thomasjbradley

Thanks for your help,
Jess

**Comment by thomasjbradley** [comment]
I think it’s because you’re using `%` for the coordinates. The `left` & `right` are great uses. But using `%` for the `top` doesn’t make sense in this scenario. **Switch all `top` coordinates to use `px`**
